name: pylint
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: edmerrett/pylint-action:latest
      credentials:
        username: ${{ secrets.DOCKER_HUB_ID}}
        password: ${{ secrets.DOCKER_HUB_TOKEN}}
    name: Pylint Linting Checker
    steps:
      - uses: actions/checkout@v2
      - run: |
          pylint --version
          pylint *.py --rcfile .pylintrc --output-format colorized || pylint-exit $?
        name: Run Pylint
